apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::192990275288:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-wJf1xBXru7R3
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::192990275288:user/sai
      username: sai
kind: ConfigMap
metadata:
  creationTimestamp: "2025-11-30T08:34:06Z"
  name: aws-auth
  namespace: kube-system
  uid: adade83a-3de3-40e6-bc33-82e35d2a1078